name: audiodream
channels:
  - conda-forge
  - anaconda
dependencies:
  - tensorflow-cpu
  - numpy
  - scipy
  - six
  - resampy
  - jupyter
  - matplotlib
  - pip
  - pip:
    - soundfile
    - tf-nightly-gpu
    - gdown
